#!/usr/bin/env python3

# Watchful Snake is a MySQL BinLog to Redis Streams Data Pipe.

# Watchful Snake is licensed under the
# GNU General Public License Version 3.
# Dimitar D. Mitov 2020
# https://github.com/ddmitov/watchful-snake

# Python Standard Library modules:
import json

# PyPI modules:
import redis

# GLOBAL CONSTANTS: #
#####################
# MYSQL_BINLOG_SLAVE_UUID
# can be generated by the 'uuidgen' utility:
MYSQL_BINLOG_SLAVE_UUID = 'e7d14803-b12f-45eb-9c33-abd2e5e9ac77'
REDIS_URL = '127.0.0.1'
REDIS_PORT = 6379
REDIS_PASSWORD = ''

MYSQL_SETTINGS = {
    'connection': {
        'host': '127.0.0.1',
        'port': 3306,
        'user': 'tester',
        'passwd': 'tralala'
    },
    'schemas': [
        'initial_testing'
    ],
    'tables': [
        'persons'
    ]
}


def main():
    redis_server = redis.Redis(
        host=REDIS_URL,
        port=REDIS_PORT,
        password=REDIS_PASSWORD
    )

    try:
        redis_server.set(
            MYSQL_BINLOG_SLAVE_UUID + ':mysql:settings',
            json.dumps(MYSQL_SETTINGS)
        )
    except (ConnectionRefusedError, redis.ConnectionError):
        print('No Redis!')
        exit(1)

    redis_server.close()


if __name__ == '__main__':
    main()
